theme: jekyll-theme-dinky
title: This Website is under construction
description: Welcome to my GitHub Pages site!

name: "Ankita Das"
job: "Data Analyst"

address: Toronto. Canada
linkedin_username: Ankita-Das-Data
github_username: AnkitaDasData
